import { TowJob, HistoryEntry, TowStats } from "../types/types";

export const ApiJobs: TowJob[] = [
  {
    id: "j1",
    vehicleModel: "Emperor",
    plateOrTag: "8XKQ2741",
    ownerName: "David Martinez",
    reason: "Engine failure",
    jobType: "tow",
    distance: "0.8mi",
    payAmount: 310,
    tip: "// Engine failure jobs run long — hook up before you lower the bed",
  },
  {
    id: "j2",
    vehicleModel: "Futo",
    plateOrTag: "3PLK9920",
    ownerName: "Sarah Johnson",
    reason: "Flat tire",
    jobType: "fix",
    distance: "1.4mi",
    payAmount: 175,
    tip: "// Flat tires are quick — no bed needed, winch arm only",
  },
  {
    id: "j3",
    vehicleModel: "Blista",
    plateOrTag: "7HNM4401",
    ownerName: "Mike Williams",
    reason: "Overheating",
    jobType: "tow",
    distance: "2.1mi",
    payAmount: 240,
    tip: "// Let the engine cool before loading — customer gets anxious",
  },
  {
    id: "j4",
    vehicleModel: "Sultan RS",
    plateOrTag: "CONTRACT",
    ownerName: "???",
    reason: "Racer needs pull",
    jobType: "contract",
    distance: "3.2mi",
    payAmount: 520,
    special: true,
    tip: "// High-value contract — deliver in under 10 mins for a bonus",
  },
  {
    id: "j5",
    vehicleModel: "???",
    plateOrTag: "???",
    ownerName: "???",
    reason: "???",
    jobType: "locked",
    distance: "???",
    payAmount: 0,
    locked: true,
  },
];

export const ApiHistory: HistoryEntry[] = [
  {
    id: "h0",
    ownerName: "Tommy R.",
    vehicleModel: "Sultan RS",
    location: "Grove St",
    timeAgo: "1h ago",
    status: "contract",
    payAmount: 520,
    special: true,
    repeatLine: "towed 3 times — contact unlocked",
  },
  {
    id: "h1",
    ownerName: "Tony R.",
    vehicleModel: "Elegy",
    location: "Mirror Park",
    timeAgo: "2h ago",
    status: "done",
    payAmount: 400,
  },
  {
    id: "h2",
    ownerName: "Sara M.",
    vehicleModel: "Zentorno",
    location: "Del Perro",
    timeAgo: "3h ago",
    status: "done",
    payAmount: 320,
    repeatLine: "towed 2 times",
  },
  {
    id: "h3",
    ownerName: "Carl D.",
    vehicleModel: "Bison",
    location: "Blaine County",
    timeAgo: "4h ago",
    status: "failed",
    payAmount: 0,
  },
];

export const ApiStats: TowStats = {
  jobsCompleted: 12,
  streak: 3,
  totalEarnings: 4850,
  avgPay: 404,
  repPoints: 42,
  repTier: "Reliable",
};
