Config = Config or {}

-- Authorized hosting providers for item images, avoid the use of Discord or Imgur
Config.Hostings = {
    "fivemerr", "fivemanage", "i.fmfile.com",
}

-- Products Tab
Config.NoCustomItems = { -- This jobs won't be able to access Product tab and register new items:
    ['police'] = true,
    ['ambulance'] = true,
    ['taxi'] = true,
    ['mechanic'] = true,
}

-- Supplies Tab
Config.UseSupplies = true -- Allows businesses to buy ingredients, set false to disable it globally
Config.NoSuppliesTab = { -- This jobs won't be able to access Supplies tab and buy ingredients
    ['police'] = true,
    ['ambulance'] = true,
    ['taxi'] = true,
    ['mechanic'] = true,
}

-- Deliveries Tab
Config.NoDeliveriesTab = { -- Use this to block specific jobs from accessing Deliveries
    ['police'] = true,
    ['ambulance'] = true,
    ['taxi'] = true,
    ['mechanic'] = true,
}

-- Posters Tab
Config.PosterJobs = { -- A table with all the jobs that can access the Poster tab in Business APP // they still need the poster zone generated by an admin
    ['uwucafe'] = true,
    ['burgershot'] = true,
}

-- Discounts Tab
Config.BlacklistedDiscounts = { -- blacklist jobs from accessing the Discounts tab
    ['police'] = true,
    ['ambulance'] = true,
    ['taxi'] = true,
    ['mechanic'] = true,
}

-- Players from this list won't be able to review any business, use it to blacklist trolls who leaves negative reviews for no reason
Config.BlacklistedPlayers = {
    -- For QBCore add the citizenid
    -- For ESX the player identifier from users table (char1:example123)
    -- For your custom framework whatever identifier you use in getIdentifier export (laptop/server/framework/exports.lua)
    ['identifier123'] = true,
    ['char1:aosdhoashd'] = true,
}