import { SelectType } from "../types/types";

export const ApiJob: SelectType[] = [
  { label: "EMS", value: "ambulance" },
  { label: "bahamas", value: "bahamas" },
  { label: "ballas", value: "ballas" },
  { label: "Banker", value: "banker" },
  { label: "bigcustoms", value: "bigcustoms" },
  { label: "burgershot", value: "burgershot" },
  { label: "Cardealer", value: "cardealer" },
  { label: "catcafe", value: "catcafe" },
  { label: "cookies", value: "cookies" },
  { label: "fastcustoms", value: "fastcustoms" },
  { label: "Fisherman", value: "fisherman" },
  { label: "fogonburger", value: "fogonburger" },
  { label: "Fueler", value: "fueler" },
  { label: "Gym Plaza", value: "gym1" },
  { label: "Gym Pump & Run", value: "gym2" },
  { label: "hookies", value: "hookies" },
  { label: "Hospital cafe", value: "hospital_cafe" },
  { label: "Hotdog Shop", value: "hotdog" },
  { label: "Lumberjack", value: "lumberjack" },
  { label: "Mecanico", value: "mecanico" },
  { label: "Mechanic", value: "mechanic" },
  { label: "Miner", value: "miner" },
  { label: "Ambulance", value: "offambulance" },
  { label: "Fuera de Servicio", value: "offduty" },
  { label: "Hotdog Shop (Fuera de Servicio)", value: "offhotdog" },
  { label: "Pizza Shop Fuera de Servicio", value: "offpizza" },
  { label: "Tacos Shop Fuera de Servicio", value: "offtacos" },
  { label: "Car Wash Fuera De Servicio", value: "offwasher" },
  { label: "Pizza Shop", value: "pizza" },
  { label: "LSPD", value: "police" },
  { label: "realestate", value: "realestate" },
  { label: "Reporter", value: "reporter" },
  { label: "Sheriff", value: "sheriff" },
  { label: "Butcher", value: "slaughterer" },
  { label: "speedhunters", value: "speedhunters" },
  { label: "sportcustoms", value: "sportcustoms" },
  { label: "srtcustoms", value: "srtcustoms" },
  { label: "Tacos Shop", value: "tacos" },
  { label: "Tailor", value: "tailor" },
  { label: "Taller", value: "taller" },
  { label: "Tattoo Shop (1)", value: "tattoo1" },
  { label: "Tattoo Shop (2)", value: "tattoo2" },
  { label: "Tattoo Shop (3)", value: "tattoo3" },
  { label: "Tattoo Shop (4)", value: "tattoo4" },
  { label: "Tattoo Shop (5)", value: "tattoo5" },
  { label: "Tattoo Shop (6)", value: "tattoo6" },
  { label: "Taxi", value: "taxi" },
  { label: "underground", value: "underground" },
  { label: "Unemployed", value: "unemployed" },
  { label: "unicorn", value: "unicorn" },
  { label: "Car Wash", value: "washer" },
  { label: "weastcoast", value: "weastcoast" },
];
