import { BillingType, BillingItem } from "../types/types";

export const ApiPremadeItems: BillingItem[] = [
  { item: "Espresso", price: 20 },
  { item: "Latte", price: 25 },
  { item: "Cappuccino", price: 27 },
  { item: "Americano", price: 22 },
  { item: "Mocha", price: 30 },
  { item: "Macchiato", price: 28 },
  { item: "Iced Coffee", price: 26 },
  { item: "Cold Brew", price: 32 },
  { item: "Matcha Latte", price: 34 },
  { item: "Chai Latte", price: 29 },
  { item: "Hot Chocolate", price: 24 },
  { item: "Green Tea", price: 18 },
  { item: "Black Tea", price: 16 },
  { item: "Lemonade", price: 21 },
  { item: "Strawberry Smoothie", price: 33 },
  { item: "Vanilla Milkshake", price: 35 },
  { item: "Blueberry Muffin", price: 17 },
  { item: "Chocolate Croissant", price: 19 },
  { item: "Butter Croissant", price: 18 },
  { item: "Bagel with Cream Cheese", price: 20 },
  { item: "Avocado Toast", price: 38 },
  { item: "Ham & Cheese Sandwich", price: 36 },
  { item: "Turkey Club Sandwich", price: 37 },
  { item: "Grilled Cheese", price: 25 },
  { item: "Caesar Salad", price: 30 },
  { item: "Chicken Wrap", price: 34 },
  { item: "Veggie Wrap", price: 32 },
  { item: "Fruit Bowl", price: 22 },
  { item: "Energy Bar", price: 15 },
  { item: "Bottled Water", price: 10 },
];

export const ApiBilling: BillingType[] = [
  {
    invoiceid: "INV0001",
    customerIdentifier: "abc123",
    customerName: "Client 1",
    customerPhone: "7036193",
    senderName: "Avilchiis",
    senderIdentifier: "uwucafe",
    amount: 8442,
    title: "Full Tune-Up",
    description: [
      { item: "Spoiler Install", price: 3381 },
      { item: "Nitrous System", price: 2550 },
      { item: "Exhaust Upgrade", price: 2511 },
      { item: "Sushi", price: 2511 },
    ],
    issued: "06/23/2025",
    paid: false,
  },
  {
    invoiceid: "INV0002",
    customerIdentifier: "char456",
    customerName: "Samantha Blue",
    customerPhone: "555-0102",
    senderName: "Avilchiis",
    senderIdentifier: "uwucafe",
    amount: 120,
    title: "Breakfast Catering",
    description: [
      { item: "Coffee Espresso", price: 40 },
      { item: "Pancakes Stack", price: 80 },
    ],
    issued: "01/10/2026",
    paid: true,
  },
  {
    invoiceid: "INV0003",
    customerIdentifier: "foxy789",
    customerName: "Isaiah King",
    customerPhone: "555-9988",
    senderName: "Lucho",
    senderIdentifier: "uwucafe",
    amount: 550,
    title: "Engine Repair",
    description: [
      { item: "Oil Change", price: 150 },
      { item: "Spark Plugs", price: 400 },
    ],
    issued: "01/15/2026",
    paid: false,
  },
  {
    invoiceid: "INV0004",
    customerIdentifier: "neon001",
    customerName: "Renata Flores",
    customerPhone: "555-2233",
    senderName: "Avilchiis",
    senderIdentifier: "uwucafe",
    amount: 2100,
    title: "Turbo Kit Install",
    description: [
      { item: "Turbocharger", price: 1800 },
      { item: "Labor Fee", price: 300 },
    ],
    issued: "01/20/2026",
    paid: true,
  },
  {
    invoiceid: "INV0005",
    customerIdentifier: "sky222",
    customerName: "Bruno Mars",
    customerPhone: "555-7777",
    senderName: "Valeria",
    senderIdentifier: "uwucafe",
    amount: 45,
    title: "Quick Snack",
    description: [
      { item: "Bacon Burger", price: 25 },
      { item: "Soda Large", price: 20 },
    ],
    issued: "01/22/2026",
    paid: false,
  },
  {
    invoiceid: "INV0006",
    customerIdentifier: "ghost333",
    customerName: "Leo Dash",
    customerPhone: "555-4411",
    senderName: "Avilchiis",
    senderIdentifier: "uwucafe",
    amount: 3200,
    title: "Body Kit Painting",
    description: [
      { item: "Matte Black Paint", price: 2000 },
      { item: "Clear Coat", price: 1200 },
    ],
    issued: "01/25/2026",
    paid: false,
  },
  {
    invoiceid: "INV0007",
    customerIdentifier: "ruby444",
    customerName: "Angie Rose",
    customerPhone: "555-8855",
    senderName: "Samantha",
    senderIdentifier: "uwucafe",
    amount: 85,
    title: "Afternoon Tea",
    description: [
      { item: "Green Tea", price: 35 },
      { item: "Mochi Set", price: 50 },
    ],
    issued: "01/28/2026",
    paid: true,
  },
  {
    invoiceid: "INV0008",
    customerIdentifier: "bolt555",
    customerName: "Carlos Fast",
    customerPhone: "555-3322",
    senderName: "Avilchiis",
    senderIdentifier: "uwucafe",
    amount: 1500,
    title: "Nitrous Refill",
    description: [
      { item: "NOS Bottle", price: 1000 },
      { item: "Valve Check", price: 500 },
    ],
    issued: "02/02/2026",
    paid: true,
  },
  {
    invoiceid: "INV0009",
    customerIdentifier: "vibe666",
    customerName: "Vicky V",
    customerPhone: "555-1199",
    senderName: "Renata",
    senderIdentifier: "uwucafe",
    amount: 1200,
    title: "Tire Replacement",
    description: [{ item: "Drift Tires x4", price: 1200 }],
    issued: "02/05/2026",
    paid: false,
  },
  {
    invoiceid: "INV0010",
    customerIdentifier: "ace777",
    customerName: "Jack Spade",
    customerPhone: "555-0077",
    senderName: "Avilchiis",
    senderIdentifier: "uwucafe",
    amount: 5000,
    title: "Custom Wrap",
    description: [
      { item: "Gold Chrome Wrap", price: 4500 },
      { item: "Surface Prep", price: 500 },
    ],
    issued: "02/08/2026",
    paid: true,
  },
  {
    invoiceid: "INV0011",
    customerIdentifier: "luna888",
    customerName: "Luna Moon",
    customerPhone: "555-4422",
    senderName: "Valeria",
    senderIdentifier: "uwucafe",
    amount: 30,
    title: "Coffee Break",
    description: [{ item: "Caramel Latte", price: 30 }],
    issued: "02/10/2026",
    paid: true,
  },
  {
    invoiceid: "INV0012",
    customerIdentifier: "iron999",
    customerName: "Tony Stark",
    customerPhone: "555-3000",
    senderName: "Avilchiis",
    senderIdentifier: "uwucafe",
    amount: 950,
    title: "Suspension Tune",
    description: [
      { item: "Lowering Springs", price: 600 },
      { item: "Alignment", price: 350 },
    ],
    issued: "02/12/2026",
    paid: false,
  },
  {
    invoiceid: "INV0013",
    customerIdentifier: "zero101",
    customerName: "Ken Kaneki",
    customerPhone: "555-1010",
    senderName: "Lucho",
    senderIdentifier: "uwucafe",
    amount: 200,
    title: "Late Night Dinner",
    description: [
      { item: "Ramen Special", price: 120 },
      { item: "Gyoza Side", price: 80 },
    ],
    issued: "02/14/2026",
    paid: true,
  },
  {
    invoiceid: "INV0014",
    customerIdentifier: "fox202",
    customerName: "Fox Mulder",
    customerPhone: "555-5551",
    senderName: "Avilchiis",
    senderIdentifier: "uwucafe",
    amount: 4500,
    title: "Brake System Upgrade",
    description: [
      { item: "Ceramic Disks", price: 3500 },
      { item: "Red Calipers", price: 1000 },
    ],
    issued: "02/16/2026",
    paid: false,
  },
  {
    invoiceid: "INV0015",
    customerIdentifier: "neo303",
    customerName: "Thomas A",
    customerPhone: "555-1337",
    senderName: "Samantha",
    senderIdentifier: "uwucafe",
    amount: 60,
    title: "Tech Support Meal",
    description: [
      { item: "Energy Drink Box", price: 40 },
      { item: "Sandwich", price: 20 },
    ],
    issued: "02/18/2026",
    paid: true,
  },
  {
    invoiceid: "INV0016",
    customerIdentifier: "hulk404",
    customerName: "Bruce Banner",
    customerPhone: "555-0800",
    senderName: "Avilchiis",
    senderIdentifier: "uwucafe",
    amount: 150,
    title: "Vehicle Checkup",
    description: [{ item: "Safety Inspection", price: 150 }],
    issued: "02/20/2026",
    paid: false,
  },
  {
    invoiceid: "INV0017",
    customerIdentifier: "cat505",
    customerName: "Selina Kyle",
    customerPhone: "555-9000",
    senderName: "Renata",
    senderIdentifier: "uwucafe",
    amount: 500,
    title: "Security Install",
    description: [{ item: "Alarm System", price: 500 }],
    issued: "02/21/2026",
    paid: true,
  },
  {
    invoiceid: "INV0018",
    customerIdentifier: "wid606",
    customerName: "Natasha R",
    customerPhone: "555-0000",
    senderName: "Avilchiis",
    senderIdentifier: "uwucafe",
    amount: 1800,
    title: "Transmission Repair",
    description: [
      { item: "Gearbox Parts", price: 1300 },
      { item: "Labor", price: 500 },
    ],
    issued: "02/22/2026",
    paid: false,
  },
  {
    invoiceid: "INV0019",
    customerIdentifier: "bat707",
    customerName: "Wayne Bruce",
    customerPhone: "555-1939",
    senderName: "Lucho",
    senderIdentifier: "uwucafe",
    amount: 12000,
    title: "Advanced Armor",
    description: [
      { item: "Reinforced Plates", price: 10000 },
      { item: "Bulletproof Tires", price: 2000 },
    ],
    issued: "02/23/2026",
    paid: true,
  },
  {
    invoiceid: "INV0020",
    customerIdentifier: "thor808",
    customerName: "Odinson Thor",
    customerPhone: "555-1001",
    senderName: "Avilchiis",
    senderIdentifier: "uwucafe",
    amount: 75,
    title: "Mjolnir Party Meal",
    description: [
      { item: "Ale Mug x5", price: 50 },
      { item: "Large Steak", price: 25 },
    ],
    issued: "02/24/2026",
    paid: false,
  },
];
