import { OrderType } from "../types/types";

export const ApiOrder: OrderType = {
  customerName: "Carlos Roberto Diaz",
  identifier: "abc123",
  cart: [
    {
      price: 5,
      label: "UwU Milkshake",
      type: "drink",
      ingredients: ["sugar", "chocolate", "milk", "ice"],
      toUse: [],
      name: "uwumilkshake",
      amount: 1,
    },
    {
      price: 5,
      label: "UwU Milkshake",
      amount: 1,
      type: "drink",
      ingredients: ["sugar", "chocolate", "milk", "ice"],
      toUse: ["sugar", "milk"],
      name: "uwumilkshake",
    },
    {
      price: 5,
      amount: 1,
      label: "UwU Milkshake",
      type: "drink",
      ingredients: ["sugar", "chocolate", "milk", "ice"],
      toUse: ["sugar", "milk", "ice"],
      name: "uwumilkshake",
    },
    {
      price: 1,
      label: "UwU Box",
      amount: 1,
      type: "box",
      ingredients: [],
      toUse: [],
      name: "uwubox",
    },
    {
      price: 1,
      amount: 1,
      label: "UwU Box",
      type: "box",
      ingredients: [],
      toUse: [],
      name: "uwubox",
    },
  ],
  order: 1,
  generated: 1751404166,
};

export const ApiOrders: OrderType[] = [
  {
    customerName: "Avilchiis 1",
    identifier: "abc123",
    cart: [
      {
        price: 5,
        amount: 1,
        label: "UwU Milkshake",
        type: "drink",
        ingredients: ["sugar", "chocolate", "milk", "ice"],
        toUse: [],
        name: "uwumilkshake",
      },
      {
        price: 5,
        amount: 1,
        label: "UwU Milkshake",
        type: "drink",
        ingredients: ["sugar", "chocolate", "milk", "ice"],
        toUse: ["sugar", "milk"],
        name: "uwumilkshake",
      },
      {
        price: 5,
        amount: 1,
        label: "UwU Milkshake",
        type: "drink",
        ingredients: ["sugar", "chocolate", "milk", "ice"],
        toUse: ["sugar", "milk", "ice"],
        name: "uwumilkshake",
      },
      {
        amount: 1,
        price: 1,
        label: "UwU Box",
        type: "box",
        ingredients: [],
        toUse: [],
        name: "uwubox",
      },
      {
        price: 1,
        amount: 1,
        label: "UwU Box",
        type: "box",
        ingredients: [],
        toUse: [],
        name: "uwubox",
      },
    ],
    order: 1,
    generated: 1751404166,
  },
  {
    customerName: "Avilchiis 2",
    identifier: "abc1234",
    cart: [
      {
        price: 6,
        amount: 1,
        label: "Strawberry Frappe",
        type: "drink",
        ingredients: ["strawberry", "milk", "ice", "sugar"],
        toUse: ["milk", "ice"],
        name: "strawfrappe",
      },
      {
        price: 2,
        amount: 1,
        label: "UwU Cookie",
        type: "food",
        ingredients: ["sugar", "chocolate", "flour", "egg"],
        toUse: [],
        name: "uwucookie",
      },
    ],
    order: 2,
    generated: 1751404190,
  },
  {
    customerName: "Avilchiis 3",
    identifier: "abc12333",
    cart: [
      {
        price: 3,
        amount: 1,
        label: "UwU Tea",
        type: "drink",
        ingredients: ["tea", "sugar", "water"],
        toUse: ["tea", "water"],
        name: "uwutea",
      },
    ],
    order: 3,
    generated: 1751404203,
  },
  {
    customerName: "Avilchiis 4",
    identifier: "a11",
    cart: [
      {
        price: 7,
        amount: 1,
        label: "UwU Pancakes",
        type: "food",
        ingredients: ["flour", "egg", "milk", "sugar", "butter"],
        toUse: ["flour", "egg", "milk"],
        name: "uwupancake",
      },
      {
        price: 1,
        label: "UwU Box",
        type: "box",
        amount: 1,
        ingredients: [],
        toUse: [],
        name: "uwubox",
      },
    ],
    order: 4,
    generated: 1751404225,
  },
  {
    customerName: "Avilchiis 5",
    identifier: "abc123bb",
    cart: [
      {
        price: 4,
        label: "UwU Coffee",
        amount: 1,
        type: "drink",
        ingredients: ["coffee_beans", "water", "milk"],
        toUse: ["coffee_beans", "water"],
        name: "uwucoffee",
      },
    ],
    order: 5,
    generated: 1751404240,
  },
  {
    customerName: "Avilchiis 6",
    identifier: "abc11123",
    cart: [
      {
        price: 6,
        label: "UwU Smoothie",
        amount: 1,
        type: "drink",
        ingredients: ["banana", "milk", "ice", "sugar"],
        toUse: ["banana", "milk"],
        name: "uwusmoothie",
      },
      {
        price: 1,
        label: "UwU Box",
        type: "box",
        ingredients: [],
        toUse: [],
        amount: 1,
        name: "uwubox",
      },
    ],
    order: 6,
    generated: 1751404255,
  },
  {
    customerName: "Avilchiis 7",
    identifier: "abc12883",
    cart: [
      {
        price: 5,
        amount: 1,
        label: "UwU Matcha",
        type: "drink",
        ingredients: ["matcha_powder", "milk", "ice"],
        toUse: ["matcha_powder", "milk"],
        name: "uwumatcha",
      },
    ],
    order: 7,
    generated: 1751404272,
  },
  {
    customerName: "Avilchiis 9",
    identifier: "a109",
    cart: [
      {
        price: 3,
        label: "UwU Rice Bowl",
        amount: 1,
        type: "food",
        ingredients: ["rice", "egg", "seaweed"],
        toUse: ["rice", "egg"],
        name: "uwuricebowl",
      },
    ],
    order: 9,
    generated: 1751404305,
  },
  {
    customerName: "Avilchiis 10",
    identifier: "abc1091",
    cart: [
      {
        price: 5,
        label: "UwU Choco Donut",
        amount: 1,
        type: "food",
        ingredients: ["flour", "chocolate", "sugar"],
        toUse: ["flour", "chocolate"],
        name: "uwuchocodonut",
      },
    ],
    order: 10,
    generated: 1751404320,
  },
];
