import { IngredientsType, JobItem, SelectType } from "../types/types";

export const ApiIngredients: IngredientsType[] = [
  {
    value: "bacon",
    type: ["food", "drink", "joint", "alcohol"],
    jobs: ["burgershot"],
    effects: ["alcohol"],
    label: "Bacon",
    price: 1,
  },
  {
    value: "banana",
    type: ["drink", "food", "joint"],
    effects: ["alcohol"],
    label: "Banana",
    price: 1,
    jobs: [],
  },
  {
    value: "blueberry",
    type: ["food"],
    effects: ["alcohol"],
    label: "Blueberry",
    price: 1,
    jobs: [],
  },
  {
    value: "bread",
    type: ["food"],
    label: "Bread",
    price: 1,
    effects: ["alcohol"],
    jobs: [],
  },
  {
    value: "bun",
    type: ["food"],
    label: "Bun",
    price: 1,
    effects: ["alcohol"],
    jobs: [],
  },
  {
    value: "butter",
    type: ["food"],
    label: "Butter",
    price: 1,
    effects: ["alcohol"],
    jobs: [],
  },
  {
    value: "caramel",
    type: ["drink", "food"],
    label: "Caramel",
    effects: ["alcohol"],
    price: 1,
    jobs: [],
  },
  {
    value: "cheese",
    type: ["food"],
    label: "Cheese",
    price: 1,
    effects: ["alcohol"],
    jobs: [],
  },
  {
    value: "chocolate",
    type: ["drink", "food"],
    label: "Chocolate",
    effects: ["alcohol"],
    price: 1,
    jobs: [],
  },
  {
    value: "coffee_beans",
    type: ["drink"],
    label: "Coffee Beans",
    price: 1,
    effects: ["alcohol"],
    jobs: [],
  },
  {
    value: "croutons",
    type: ["food"],
    label: "Croutons",
    price: 1,
    effects: ["alcohol"],
    jobs: [],
  },
  {
    value: "egg",
    type: ["food"],
    label: "Egg",
    price: 1,
    effects: ["alcohol"],
    jobs: [],
  },
  {
    value: "espresso",
    type: ["drink"],
    label: "Espresso",
    effects: ["alcohol"],
    price: 1,
    jobs: [],
  },
  {
    value: "flour",
    type: ["food"],
    label: "Flour",
    effects: ["alcohol"],
    price: 1,
    jobs: [],
  },
  {
    value: "ham",
    type: ["food"],
    label: "Ham",
    effects: ["alcohol"],
    price: 1,
    jobs: [],
  },
  {
    value: "ice",
    type: ["drink"],
    label: "Ice",
    effects: ["alcohol"],
    price: 1,
    jobs: [],
  },
  {
    value: "ketchup",
    type: ["food"],
    label: "Ketchup",
    effects: ["alcohol"],
    price: 1,
    jobs: [],
  },
  {
    value: "lemon",
    type: ["drink", "food"],
    effects: ["alcohol"],
    label: "Lemon",
    price: 1,
    jobs: [],
  },
  {
    value: "lettuce",
    type: ["food"],
    effects: ["alcohol"],
    label: "Lettuce",
    price: 1,
    jobs: [],
  },
  {
    value: "matcha_powder",
    type: ["drink"],
    label: "Matcha Powder",
    effects: ["alcohol"],
    price: 1,
    jobs: [],
  },
  {
    value: "milk",
    type: ["drink", "food"],
    label: "Milk",
    price: 1,
    effects: ["alcohol"],
    jobs: [],
  },
  {
    value: "mustard",
    type: ["food"],
    label: "Mustard",
    price: 1,
    effects: ["alcohol"],
    jobs: [],
  },
  {
    value: "oil",
    type: ["food"],
    label: "Oil",
    price: 1,
    effects: ["alcohol"],
    jobs: [],
  },
  {
    value: "potato",
    type: ["food"],
    label: "Potato",
    price: 1,
    effects: ["alcohol"],
    jobs: [],
  },
  {
    value: "rice",
    type: ["food"],
    label: "Rice",
    price: 1,
    effects: ["alcohol"],
    jobs: [],
  },
  {
    value: "salmon",
    type: ["food"],
    label: "Salmon",
    price: 1,
    effects: ["alcohol"],
    jobs: [],
  },
  {
    value: "salt",
    type: ["food"],
    label: "Salt",
    price: 1,
    effects: ["alcohol"],
    jobs: [],
  },
  {
    value: "sausage",
    type: ["food"],
    label: "Sausage",
    price: 1,
    effects: ["alcohol"],
    jobs: [],
  },
  {
    value: "seaweed",
    type: ["food"],
    label: "Seaweed",
    price: 1,
    effects: ["alcohol"],
    jobs: [],
  },
  {
    value: "spinach",
    type: ["food"],
    label: "Spinach",
    price: 1,
    effects: ["alcohol"],
    jobs: [],
  },
  {
    value: "strawberry",
    type: ["drink", "food"],
    label: "Strawberry",
    effects: ["alcohol"],
    price: 1,
    jobs: [],
  },
  {
    value: "sugar",
    type: ["drink", "food"],
    effects: ["alcohol"],
    label: "Sugar",
    price: 1,
    jobs: [],
  },
  {
    value: "syrup",
    type: ["drink", "food"],
    effects: ["alcohol"],
    label: "Syrup",
    price: 1,
    jobs: [],
  },
  {
    value: "tapioca",
    type: ["drink", "food"],
    effects: ["alcohol"],
    label: "Tapioca",
    price: 1,
    jobs: [],
  },
  {
    value: "tea",
    type: ["drink"],
    label: "Tea",
    effects: ["alcohol"],
    price: 1,
    jobs: [],
  },
  {
    value: "tea_leaves",
    type: ["drink"],
    label: "Tea Leaves",
    effects: ["alcohol"],
    price: 1,
    jobs: [],
  },
  {
    value: "tomato",
    type: ["food"],
    label: "Tomato",
    price: 1,
    effects: ["alcohol"],
    jobs: [],
  },
  {
    value: "vanilla",
    type: ["drink", "food"],
    label: "Vanilla",
    effects: ["alcohol"],
    price: 1,
    jobs: [],
  },
  {
    value: "water",
    type: ["drink"],
    label: "Water",
    price: 1,
    effects: ["alcohol"],
    jobs: [],
  },
];

export const ApiTypes: SelectType[] = [
  {
    value: "drink",
    label: "Drink",
  },
  {
    value: "food",
    label: "Food",
  },
  {
    value: "joint",
    label: "Joint",
  },
  {
    value: "others",
    label: "Others",
  },
  {
    value: "box",
    label: "Boxes",
  },
  {
    value: "alcohol",
    label: "Alcohol",
  },
];

export const ApiAnimations: IngredientsType[] = [
  {
    value: "burger",
    type: ["food"],
    label: "Burger",
    jobs: [],
  },
  {
    value: "soda",
    type: ["drink"],
    label: "Soda",
    jobs: [],
  },
  {
    value: "sandwich",
    type: ["food"],
    label: "Sandwich",
    jobs: [],
  },
];

export const ApiJobItems: JobItem[] = [
  {
    ingredients: [
      "banana",
      "milk",
      "coffee_beans",
      "matcha_powder",
      "flour",
      "egg",
      "sugar",
    ],
    image: "",
    type: "food",
    description: "Best burger in town",
    weight: "746",
    price: 17,
    label: "Test Burger",
    name: "testburger",
    job: "uwucafe",
    prop: "burger",
    toUse: [],
  },
  {
    ingredients: ["milk", "coffee_beans"],
    image: "",
    type: "drink",
    description: "Smooth and creamy espresso",
    weight: "379",
    price: 11,
    label: "Espresso",
    name: "espresso",
    job: "uwucafe",
    prop: "coffee",
  },
  {
    ingredients: ["matcha_powder", "milk"],
    image: "",
    type: "drink",
    description: "Chilled matcha latte, refreshing and energizing",
    weight: "885",
    price: 16,
    label: "Iced Matcha Latte",
    name: "matchalatte",
    job: "uwucafe",
    prop: "cup",
  },
  {
    ingredients: ["flour", "egg", "sugar"],
    image: "",
    type: "food",
    description: "Freshly baked pancakes topped with syrup",
    weight: "735",
    price: 7,
    label: "Pancakes",
    name: "pancakes",
    job: "uwucafe",
    prop: "pancake",
  },
  {
    ingredients: ["rice", "salmon", "seaweed"],
    image: "",
    type: "food",
    description: "Delicious salmon sushi rolls",
    weight: "502",
    price: 1500000,
    label: "Salmon Sushi",
    name: "salmonsushi",
    job: "uwucafe",
    prop: "sushi",
  },
  {
    ingredients: ["tea_leaves", "lemon", "sugar"],
    image: "",
    type: "drink",
    description: "Homemade lemon iced tea",
    weight: "970",
    price: 11,
    label: "Lemon Iced Tea",
    name: "lemontea",
    job: "uwucafe",
    prop: "glass",
  },
  {
    ingredients: ["strawberry", "milk", "sugar"],
    image: "",
    type: "drink",
    description: "Fruity and sweet strawberry smoothie",
    weight: "567",
    price: 13,
    label: "Strawberry Smoothie",
    name: "strawberrysmoothie",
    job: "uwucafe",
    prop: "smoothie",
  },
  {
    ingredients: ["bread", "cheese", "ham"],
    image: "",
    type: "food",
    description: "Classic grilled ham & cheese sandwich",
    weight: "749",
    price: 10,
    label: "Ham & Cheese",
    name: "hamcheese",
    job: "uwucafe",
    prop: "sandwich",
  },
  {
    ingredients: ["potato", "salt", "oil"],
    image: "",
    type: "food",
    description: "Crispy golden fries",
    weight: "775",
    price: 9,
    label: "French Fries",
    name: "fries",
    job: "uwucafe",
    prop: "fries",
  },
  {
    ingredients: ["flour", "sugar", "chocolate"],
    image: "",
    type: "food",
    description: "Warm chocolate chip cookies",
    weight: "820",
    price: 15,
    label: "Cookies",
    name: "cookies",
    job: "uwucafe",
    prop: "cookie",
  },
  {
    ingredients: ["flour", "egg", "blueberry"],
    image: "",
    type: "food",
    description: "Fresh muffin loaded with blueberries",
    weight: "838",
    price: 8,
    label: "Blueberry Muffin",
    name: "muffin",
    job: "uwucafe",
    prop: "muffin",
  },
  {
    ingredients: ["tea", "milk", "tapioca"],
    image: "",
    type: "drink",
    description: "Sweet and chewy bubble tea with tapioca pearls",
    weight: "615",
    price: 15,
    label: "Bubble Tea",
    name: "bubbletea",
    job: "uwucafe",
    prop: "bubbletea",
  },
  {
    ingredients: ["bread", "bacon", "lettuce", "tomato"],
    image: "",
    type: "food",
    description: "Triple layered club sandwich with bacon",
    weight: "552",
    price: 9,
    label: "Club Sandwich",
    name: "club_sandwich",
    job: "uwucafe",
    prop: "sandwich",
  },
  {
    ingredients: ["bun", "sausage", "mustard", "ketchup"],
    image: "",
    type: "food",
    description: "Classic hot dog with mustard and ketchup",
    weight: "954",
    price: 17,
    label: "Hot Dog",
    name: "hotdog",
    job: "uwucafe",
    prop: "hotdog",
  },
  {
    ingredients: ["espresso", "caramel", "milk"],
    image: "",
    type: "drink",
    description: "Rich espresso with caramel drizzle",
    weight: "981",
    price: 14,
    label: "Caramel Macchiato",
    name: "macchiato",
    job: "uwucafe",
    prop: "coffee",
  },
  {
    ingredients: ["flour", "butter"],
    image: "",
    type: "food",
    description: "Buttery, flaky croissant",
    weight: "977",
    price: 13,
    label: "Croissant",
    name: "croissant",
    job: "uwucafe",
    prop: "croissant",
  },
  {
    ingredients: ["lettuce", "croutons", "cheese"],
    image: "",
    type: "food",
    description: "Fresh salad with Caesar dressing",
    weight: "388",
    price: 12,
    label: "Caesar Salad",
    name: "salad",
    job: "uwucafe",
    prop: "bowl",
  },
  {
    ingredients: ["flour", "egg", "syrup"],
    image: "",
    type: "food",
    description: "Crispy waffles with syrup",
    weight: "648",
    price: 15,
    label: "Waffles",
    name: "waffles",
    job: "uwucafe",
    prop: "waffle",
  },
  {
    ingredients: ["spinach", "banana", "milk"],
    image: "",
    type: "drink",
    description: "Healthy smoothie with spinach and banana",
    weight: "897",
    price: 17,
    label: "Green Smoothie",
    name: "smoothie_green",
    job: "uwucafe",
    prop: "smoothie",
  },
  {
    ingredients: ["espresso", "vanilla", "milk"],
    image: "",
    type: "drink",
    description: "Espresso blended with vanilla syrup and milk",
    weight: "679",
    price: 7,
    label: "Vanilla Latte",
    name: "latte",
    job: "uwucafe",
    prop: "coffee",
  },
];
